### PR TITLE
Fix image path

### PR DESCRIPTION
**Pull request by camilonova**

### CODE REVIEW

**Comment by camilonova** [comment]
Anyone here?

**Comment by camilonova** [comment]
Hello?

**Comment by KennethAshley** [comment]
Hello Camilonova, 

Sorry for the late reply. Thanks for sending a pull request. We will review the code shortly.

**Comment by camilonova** [comment]
@KennethAshley is just one line to fix a pain when trying to collect my static assets.

**Comment by KennethAshley** [comment]
@camilonova It is one line but there are several other things we have to take into consideration.

**Comment by camilonova** [comment]
@KennethAshley can you tell what else is needed to have this merged?

**Comment by greg5green** [comment]
I'm just taking a look at it now, and maybe one of the other collaborators will disagree with me on this one, but I don't foresee us merging this commit as is. This change was to the generated css `owl.video.css` file, not the source `owl.video.scss` file, and more importantly, this change would break this icon for any user that is already using the video carousel functionality.

Perhaps something that could be merged would be creating a `owl.variables.scss` file with variables like `$image-path: './'`. The end user (you, in this case) could then import the various scss files into their project and also import an overrides file that would contain a line like `$image-path: '../'` and gain the configurability you are looking for.

I'm closing this pull request for now, but if this additional variables file is something you'd like to take a swing at, let me know and I'll re-open.

**Pull request closed without merging**
