### PR TITLE
less support

### PR DESCRIPTION
**Pull request by eparisio**
rewrite css files to less format, 
added owl.style.less to generate a unique style.css

### CODE REVIEW

**Comment by mikehdt** [comment]
From what I can tell from the Gruntfile, Owl Carousel currently builds using Sass, not Less... this may be best kept as a fork?

**Comment by eparisio** [comment]
there is #650  with a request for less support so i add it

**Comment by mikehdt** [comment]
That is correct, however your pull request is changing Owl's current Sass-based code into Less, which may not be what the maintainer intends. A similar thing exists with Bootstrap for example; they maintain both Less and Sass versions, but they are distinct forks.

Offering to entirely replace the current Sass code with Less is like swapping out a car's engine from petrol to diesel when the owner was happy with petrol (yay car analogies!). Anyway, I'm not a maintainer, just that's the way it would seem to make most sense.

**Comment by eparisio** [comment]
ah ok, i understand what did you mean.
Actually i didn't replace the sass files and in a project like this i think that the user can have bot sass and less without having them separate in two fork.
But the maintainer will decide if taking it separete or not

**Comment by greg5green** [comment]
@eparisio Thanks so much for providing this PR, but I'm not going to merge this because we don't want to maintain two different CSS-type sources.

**Pull request closed without merging**
